### ISSUE TITLE
Activating auto-imports in Python triggers NoClassDefFoundError

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-ui-swing#20]
As reported in [this question on SO](http://stackoverflow.com/q/36719710/1919049), activating (deprecated) auto-imports in Python leads to the following error being thrown:

```
[WARNING] Auto-imports are active, but deprecated.
Traceback (most recent call last):
  File "New_.py", line 33, in <module>
java.lang.NoClassDefFoundError: javax/vecmath/Point3f
```

To reproduce, run this python script with auto-imports enabled (*Edit > Auto-import (deprecated)* in the script editor):

```python
print("Foo")
```

**Comment by ctrueden** [comment]
I was able to replicate the bug on Linux with the Java-8 version of Fiji. (Sadly, on my particular OS X machine, an old version of `javax.vecmath.Point3f` is permanently available from `/System/Library/Java/Extensions/vecmath.jar`.)

However, on OS X, this Groovy script:
```groovy
// @PluginService pluginService
// @ScriptService scriptService

// Convenience method for use with Map<String, ? extends Collection<? extends Object>> objects
// In this case, AutoImporter#getDefaultImports() returns a Map<String, List<String>>
java.util.Map.metaClass.pkg {
	for (key in delegate.keySet())
		if (delegate.get(key).contains(it)) return key
}

autoImporterPlugins = pluginService.getPluginsOfType(net.imagej.ui.swing.script.AutoImporter)
println("Found " + autoImporterPlugins.size() + " AutoImporter plugins")

autoImporter = pluginService.createInstance(autoImporterPlugins.get(0))
lang = scriptService.getLanguageByName("jython")
importsMap = autoImporter.getDefaultImports()

// sanity check for ImageJ 1.x class
println("-- Searching for PlugIn --")
println(importsMap.pkg("PlugIn"))

// look for old Java 3D class
println("-- Searching for Point3f --")
println(importsMap.pkg("Point3f"))
```
outputs:
```
Found 1 AutoImporter plugins
-- Searching for PlugIn --
ij.plugin
-- Searching for Point3f --
null
```
Which has me a bit baffled!

Will return to investigate more another day.

**Comment by ctrueden** [comment]
I can no longer reproduce this bug on my system.

Perhaps relatedly, my upgrade to macOS Sierra last night wiped out everything in my `/System/Library/Java/Extensions` folder except for `MRJToolkit.jar`.

**Comment by imagejan** [comment]
@ctrueden confirmed, I also cannot reproduce the original issue (tested both on Mac OSX Yosemite and on Windows 7).

However, your example Groovy script above now throws an exception:
```
groovy.lang.MissingPropertyException: No such property: net for class: Script1
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:50)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:231)
	at Script2.run(Script2.groovy:11)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:303)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:122)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:114)
	at javax.script.AbstractScriptEngine.eval(Unknown Source)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:177)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by ctrueden** [comment]
Thanks!
