### ISSUE TITLE
SwingUI's chooseFile deadlocks on macOS

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava-ui-swing#28]
The following code deadlocks on my macOS system:
```java
final ImageJ ij = new ImageJ();
ij.launch(args);
final File file = ij.ui().chooseFile(null, FileWidget.OPEN_STYLE);
System.out.println(file);
```
The joys of the EDT!

**Comment by ctrueden** [comment]
Here is a thread dump from the deadlock:
```
Found one Java-level deadlock:
=============================
"AWT-EventQueue-0":
  waiting to lock monitor 0x00007fd21bef9a18 (object 0x00000006c07e2980, a java.awt.Component$AWTTreeLock),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007fd21bef9b78 (object 0x000000076e7cfaf8, a java.lang.Object),
  which is held by "AWT-EventQueue-0"

Java stack information for the threads listed above:
===================================================
"AWT-EventQueue-0":
	at java.awt.Component.invalidate(Component.java:2934)
	- waiting to lock <0x00000006c07e2980> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.invalidate(Container.java:1587)
	at javax.swing.JComponent.revalidate(JComponent.java:4848)
	at javax.swing.JTable.tableRowsInserted(JTable.java:4482)
	at javax.swing.JTable.tableChanged(JTable.java:4407)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:231)
	at com.apple.laf.AquaFileSystemModel$DoChangeContents.run(AquaFileSystemModel.java:458)
	- locked <0x000000076e7cfaf8> (a java.lang.Object)
	- locked <0x000000076e957a28> (a java.lang.Object)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
"main":
	at com.apple.laf.AquaFileSystemModel.getRowCount(AquaFileSystemModel.java:194)
	- waiting to lock <0x000000076e7cfaf8> (a java.lang.Object)
	at javax.swing.JTable.getRowCount(JTable.java:2662)
	at javax.swing.plaf.basic.BasicTableUI.createTableSize(BasicTableUI.java:1692)
	at javax.swing.plaf.basic.BasicTableUI.getPreferredSize(BasicTableUI.java:1733)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.ScrollPaneLayout.preferredLayoutSize(ScrollPaneLayout.java:495)
	at java.awt.Container.preferredSize(Container.java:1796)
	- locked <0x00000006c07e2980> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	- locked <0x00000006c07e2980> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.preferredSize(Container.java:1796)
	- locked <0x00000006c07e2980> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	- locked <0x00000006c07e2980> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.preferredSize(Container.java:1796)
	- locked <0x00000006c07e2980> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.getPreferredSize(Container.java:1780)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at javax.swing.BoxLayout.checkRequests(BoxLayout.java:484)
	at javax.swing.BoxLayout.layoutContainer(BoxLayout.java:425)
	- locked <0x000000076e4c2618> (a javax.swing.BoxLayout)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validate(Container.java:1630)
	- locked <0x00000006c07e2980> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.validateUnconditionally(Container.java:1667)
	- locked <0x00000006c07e2980> (a java.awt.Component$AWTTreeLock)
	at java.awt.Window.pack(Window.java:818)
	at javax.swing.JFileChooser.createDialog(JFileChooser.java:821)
	at javax.swing.JFileChooser.showDialog(JFileChooser.java:749)
	at javax.swing.JFileChooser.showOpenDialog(JFileChooser.java:656)
	at org.scijava.ui.swing.AbstractSwingUI.chooseFile(AbstractSwingUI.java:137)
	at org.scijava.ui.DefaultUIService.chooseFile(DefaultUIService.java:310)
	at sc.fiji.imageFocus.Main.main(Main.java:44)
```
